name: Deploy AFE Application

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Select the command to run'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply
          - destroy

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Set environment variables based on input
        id: set_env_vars
        run: |
          echo "TF_VAR_ghpat=${{ secrets.AFE_GH_PAT }}" >> $GITHUB_ENV
          echo "TF_VAR_appsecret=${{ secrets.APP_SECRET }}" >> $GITHUB_ENV
          echo "TF_VAR_s3_bucket=${{ vars.S3_BUCKET }}" >> $GITHUB_ENV
          echo "AWS_DEFAULT_REGION=${{ vars.AWS_DEFAULT_REGION }}" >> $GITHUB_ENV
          echo "AWS_ACCESS_KEY_ID=${{ vars.PROD_AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "TF_VAR_env=afe-prod" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Terraform commands
        run: |
          cd terraform

          terraform init -backend-config=backend-prod.tfvars
          
          if [ "${{ github.event.inputs.command }}" == "plan" ]; then
            terraform plan 
          fi
          if [ "${{ github.event.inputs.command }}" == "apply" ]; then
            terraform apply -auto-approve
          fi
          if [ "${{ github.event.inputs.command }}" == "destroy" ]; then
            terraform destroy -auto-approve
          fi